apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: colorsweb-destinationrule
  namespace: colors-web
spec:
  host: colors-api-srv.colors-api.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: colorsapi-destinationrule
  namespace: colors-api
spec:
  host: colors-web-clusterip-srv.colors-web.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL