apiVersion: v1
kind: Namespace
metadata:
  name: azure-cvm-attest

---

apiVersion: v1
kind: Pod
metadata:
  name: cvm-attestation
  namespace: azure-cvm-attest
  labels:
    app: cvm-attestation
spec:
  containers:
  - image: mcr.microsoft.com/acc/samples/cvm-attestation:1.1
    imagePullPolicy: IfNotPresent
    name: cvm-attestation
    volumeMounts:
      - mountPath: /sys/kernel/security
        name: tcg
      - mountPath: /dev/tpmrm0
        name: tpmrm0
    securityContext:
      privileged: true
  nodeSelector:
    kubernetes.azure.com/agentpool: cfdnp01
  volumes:
    - name: tcg
      hostPath:
        path: /sys/kernel/security
    - name: tpmrm0
      hostPath:
        path: /dev/tpmrm0
  restartPolicy: Never
  tolerations:
    - key: "sgx" 
      operator: "Equal" 
      value: "true" 
      effect: "NoSchedule" 

      
