apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - pls-nginx.yaml

configMapGenerator:
- name: environment-variables
  envs: [environment-properties.env]
  behavior: create
  
configurations:
  - env-var-transformer.yaml

vars:
 - name: client-id
   objref:
    kind: ConfigMap
    name: environment-variables
    apiVersion: v1
   fieldref:
    fieldpath: data.client-id

