kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-colors-web
  namespace: colors-api
spec:
  podSelector:
    matchLabels:
      app: colors-api-service
  ingress:
     - from:
        -  namespaceSelector:
            matchLabels:
              app: colors-web-service
        - namespaceSelector:
            matchLabels:
              app.kubernetes.io/name: ingress-nginx
     - ports:
        - port: 80


# Allow traffic in the Colors API namespace from namespaces with the label app: colors-web on port 80. 