FROM ubuntu:20.04 as base
RUN \
apt-get update -y && \
apt-get install build-essential -y && \
DEBIAN_FRONTEND=noninteractive apt-get install git -y 
FROM base as build
RUN git clone https://github.com/owainow/aks-zero-trust-demo.git && \
ENTRYPOINT ["bash", "/aks-zero-trust-demo/Terraform/Intial_Terraform/modules/aci/scripts/configureLinuxRunner.sh"]
