# This is a basic workflow to help you get started with Actions

name: TEMP Configure infra post deployment

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Terraform_Provision:
    # The type of runner that the job will run on
    runs-on: self-hosted
    
    
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
     # Install required packages
      - name: Install required packages.
        run: apt-get update && apt-get install unzip -y && apt-get install python3 -y && apt-get install -y gettext-base && apt-get install sudo -y && sudo apt-get install npm -y && curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash && az aks install-cli | sudo bash
      
      - name: Generate github repo url 
        run: |
            export gh_repo_url="https://github.com/repos/${{ github.repository }}"
            echo "gh_repo_url=$gh_repo_url" >> $GITHUB_ENV
    
      - name: Generate github repo url 
        run: |
            export gh_url="https://github.com/${{ github.repository }}"
            echo "gh_url=$gh_url" >> $GITHUB_ENV

      
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get AKS OIDC 
        env: 
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }} 
        run: |
            export aks_oidc_issuer="$(az aks show -n aks-oow-zerotrust -g oow-aks-zero-trust-demo --query "oidcIssuerProfile.issuerUrl" -otsv)"
            echo "aks_oidc_issuer=$aks_oidc_issuer" >> $GITHUB_ENV
      
      
      - name: Create kv workload managed identity
        env:
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }} 
        run: az identity create -g oow-aks-zero-trust-demo -n kv-wl-msi

      - name: Get client-id
        env:
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }} 
        working-directory:  /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform/modules/aks_config/nginx_files
        run: |
        
            export kv_wl_msi_clientid="$(az identity show --resource-group oow-aks-zero-trust-demo --name kv-wl-msi --query 'clientId' -otsv)"
            echo "client_id=$kv_wl_msi_clientid" >  environment-properties.env
            echo "client_id=$kv_wl_msi_clientid" >> $GITHUB_ENV


      - name: Allow to propergate - 2M Sleep
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: sleep 2m

      - name: Add Permisions to kv workload managed identity
        env:
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }} 
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform/modules/aks_config/nginx_files
        run: |
            export spID="$(az identity show --resource-group oow-aks-zero-trust-demo --name kv-wl-msi --query 'principalId' -otsv)"
            az role assignment create --assignee $spID --role 'Reader' --resource-group oow-aks-zero-trust-demo


      - name: Get Create federated-credential for application kv
        env:
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }} 
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Cluster/argocd/infrastructure/nginx
        run: |
            
            az identity federated-credential create --name fed-cred-kv-id --identity-name kv-wl-msi --resource-group  oow-aks-zero-trust-demo --issuer $aks_oidc_issuer --subject system:serviceaccount:"ingress-nginx":"ingress-nginx" --audience api://AzureADTokenExchange
      

      # Install the preferred version of Terraform CLI 
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.5
    
      - name: Enable local accounts
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        run: az aks update -g oow-aks-zero-trust-demo -n aks-oow-zerotrust --enable-local-accounts     
      # Will use cluster name & RG output instead of hard coded name  here when running full workflow
      
      - name: Get KubeConfig
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        run: az aks get-credentials -g oow-aks-zero-trust-demo -n aks-oow-zerotrust --overwrite-existing --admin
      # Will use cluster name & RG output instead of hard coded name  here when running full workflow

      
      - name: Setup sgx taint
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: az aks nodepool update --resource-group oow-aks-zero-trust-demo --cluster-name aks-oow-zerotrust --name sgxnp01 --node-taints sgx=true:NoSchedule --labels purpose=sqx

      - name: Setup Cluster for GitOps - Register Extension manager
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: az feature register --namespace Microsoft.ContainerService --name AKS-ExtensionManager
     
      - name: Setup Cluster for GitOps - Register MSFT Kubernetes
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run:   az provider register --namespace Microsoft.Kubernetes  

      - name: Setup Cluster for GitOps - Register MSFT-ContainerService
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: az provider register --namespace Microsoft.ContainerService 

      - name: Setup Cluster for GitOps - Register KubernetesConfig
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: az provider register --namespace Microsoft.KubernetesConfiguration 

      - name: Setup Cluster for GitOps - K8s  Config Upgrade
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: az extension add -n k8s-configuration --upgrade 

      - name: Setup Cluster for GitOps -  K8s Extension Upgrade
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: az extension add -n k8s-extension --upgrade

      - name: Setup Cluster for Istio - Add extension for preview
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: az extension add --name aks-preview
               
      - name: Setup Cluster for Istio - Register for feature
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run:  az feature register --namespace "Microsoft.ContainerService" --name "AzureServiceMeshPreview"

      - name: Pull NGINX images to Azure Container Registry
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: az acr import --name croowzerotrustfpbldpbu6w6bu --source registry.k8s.io/ingress-nginx/controller:v1.5.1 --image ingress-nginx-controller:latest && az acr import --name croowzerotrustfpbldpbu6w6bu --source registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343 --image ingress-nginx-webhook:latest

      - name: Install Helm
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && ./get_helm.sh
     
      - name: Install Istio 
        run: az aks mesh enable --resource-group oow-aks-zero-trust-demo --name aks-oow-zerotrust
      # Will use cluster name & RG output instead of hard coded name  here when running full workflow

      - name: Install Istio CLI
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run:  cd / && curl -L https://istio.io/downloadIstio | ISTIO_VERSION=1.17.2 sh && cd /istio-1.17.2 && chmod -R +x bin && export PATH="$PATH:/istio-1.17.2/bin" && echo "$PATH:/istio-1.17.2/bin" >> $GITHUB_PATH
     
      
      - name: Setup Cluster for Argo - Install Argo CLI
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: curl -SL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd | sudo bash

      - name: Setup Cluster for Argo - Install Apply Argo Manifest 
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: kubectl create namespace argocd && kubectl apply -f argocd.yaml -n argocd

      - name: Setup Cluster for Argo - Install Apply Argo Manifest 
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: sleep 2m

    #  - name: Flux install 
    #    working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
    #    run: az k8s-extension create -g oow-aks-zero-trust-demo -c aks-oow-zerotrust -n flux --extension-type microsoft.flux -t managedClusters --version 1.6.4

    #  - name: Configure Flux
    #    working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
    #    run: az k8s-configuration flux create -g oow-aks-zero-trust-demo -c aks-oow-zerotrust -n cluster-config --namespace cluster-config -t managedClusters --scope cluster --u https://github.com/owainow/aks-zero-trust-demo --branch master  --kustomization name=infrastructure path=./Cluster/flux-system/infrastructure prune=true --kustomization name=apps path=.Cluster/flux-system/apps prune=true dependsOn=["infrastructure"] 
     

      - name: Login to argo server
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: argocd login $(kubectl get endpoints argocd-server -n argocd --output=jsonpath='{.subsets[0].addresses[0].ip}'):8080 --username admin --password $(kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo) --insecure


      - name: Deploy ArgoCD App - Colors App
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run:  argocd app create colors-app --repo $gh_url.git --path Cluster/argocd/apps/colors-app --self-heal --sync-policy automated --auto-prune --dest-server https://kubernetes.default.svc --directory-recurse

      - name: Wait for deployment - 2 Minutes
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: sleep 2m

      - name: Deploy ArgoCD Infra - NGINX
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run:  argocd app create nginx-infra --repo $gh_url.git --path Cluster/argocd/infrastructure/nginx --self-heal --sync-policy automated --auto-prune --dest-server https://kubernetes.default.svc 

      - name: Deploy ArgoCD Infra - Wait for service to be ready
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: | 
             echo "--- Wait until Loadbalancer url is present (see https://stackoverflow.com/a/70108500/4964553)"
             until kubectl get service/ingress-nginx-controller -n ingress-nginx --output=jsonpath='{.status.loadBalancer}' | grep "ingress"; do : ; done

     
      - name: Deploy ArgoCD Infra - Istio
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run:  argocd app create istio-infra --repo $gh_url.git --path Cluster/argocd/infrastructure/istio --self-heal --sync-policy automated --auto-prune

      - name: Wait for deployment - 2 Minutes
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: sleep 2m


      - name: Deploy ArgoCD Infra - Calico
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run:  argocd app create calico-infra --repo $gh_url.git --path Cluster/argocd/infrastructure/calico --self-heal --sync-policy automated --auto-prune
    
      - name: Wait for deployment - 2 Minutes
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: sleep 2m

      - name: Deploy ArgoCD App - Remote Attest App
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run:  argocd app create attest-app --repo $gh_url.git --path Cluster/argocd/apps/cvm-python-app-remoteattest --self-heal --sync-policy automated --auto-prune 

      - name: Wait for deployment - 2 Minutes
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        run: sleep 2m

      # Run Terraform Init
      - name: Terraform Init for Intial Terraform Config
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        id: init
        env:
         ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
         ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
         ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
         ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
         RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
         STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
         CONTAINER_NAME: ${{ secrets.CONTAINER_NAME_2 }}
        run: terraform init -backend-config="storage_account_name=$STORAGE_ACCOUNT" -backend-config="container_name=$CONTAINER_NAME" -backend-config="resource_group_name=$RESOURCE_GROUP"
      
      # Run Terraform Apply with Auto Approve
      - name: Terraform Apply for Intial Terraform Config
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        run: terraform apply -auto-approve
      
      - name: Disable local accounts
        working-directory: /actions-runner/_work/aks-zero-trust-demo/aks-zero-trust-demo/Terraform/Config_Terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
        run: az aks update -g oow-aks-zero-trust-demo -n aks-oow-zerotrust --disable-local-accounts
      # Will use cluster name & RG output instead of hard coded name  here when running full workflow
      
